/**
 * File generated by Magnet rest2mobile 1.1 - May 20, 2015 11:24:35 AM
 * @see {@link http://developer.magnet.com}
 */

package com.franmondey.soundphone.model.beans;


/**
 * Generated from json example
{
  "uuid" : "41d55725-f380-0000-61c3-cf801b95ffb3",
  "track" : {
    "artwork_url" : "https://i1.sndcdn.com/artworks-000117434109-3qbumy-large.jpg",
    "comment_count" : 0,
    "commentable" : true,
    "description" : "Info+Tracklist:http://runthetrap.com/2015/05/20/too-future-guest-mix-032-ekali/\n\nEkali\nhttps://soundcloud.com/ekalimusic\nhttps://twitter.com/EkaliMusic\nhttps://www.facebook.com/ekalibeats\n\nTooFuture.\n@toofutureshop\nwww.facebook.com/toofuturexx\nwww.youtube.com/user/toofutureshop\ntwitter.com/toofuture\nwww.instagram.com/toofutureshop\nwww.toofuture.com(beta)",
    "download_count" : 0,
    "downloadable" : false,
    "embeddable_by" : "all",
    "favoritings_count" : 1,
    "genre" : "Ekali",
    "license" : "all-rights-reserved",
    "original_content_size" : 65785179,
    "original_format" : "mp3",
    "playback_count" : 8,
    "reposts_count" : 0,
    "state" : "finished",
    "streamable" : true,
    "tag_list" : "\"TooFuture\"\"Future\"\"FutureBass\"Trap",
      ...

 */

public class Collection {

  
  private String created_at;

  
  private Playlist playlist;

  
  private Track track;

  
  private String type;

  
  private User user;

  
  private String uuid;

  public String getCreated_at() {
    return created_at;
  }
  public Playlist getPlaylist() {
    return playlist;
  }
  public Track getTrack() {
    return track;
  }
  public String getType() {
    return type;
  }
  public User getUser() {
    return user;
  }
  public String getUuid() {
    return uuid;
  }

  /**
  * Builder for Collection
  **/
  public static class CollectionBuilder {
    private Collection toBuild = new Collection();

    public CollectionBuilder() {
    }

    public Collection build() {
      return toBuild;
    }

    public CollectionBuilder created_at(String value) {
      toBuild.created_at = value;
      return this;
    }
    public CollectionBuilder playlist(Playlist value) {
      toBuild.playlist = value;
      return this;
    }
    public CollectionBuilder track(Track value) {
      toBuild.track = value;
      return this;
    }
    public CollectionBuilder type(String value) {
      toBuild.type = value;
      return this;
    }
    public CollectionBuilder user(User value) {
      toBuild.user = value;
      return this;
    }
    public CollectionBuilder uuid(String value) {
      toBuild.uuid = value;
      return this;
    }
  }
}
