/**
 * File generated by Magnet rest2mobile 1.1 - May 20, 2015 11:24:35 AM
 * @see {@link http://developer.magnet.com}
 */

package com.franmondey.soundphone.model.beans;


/**
 * Generated from json example
{
  "avatar_url" : "https://i1.sndcdn.com/avatars-000060418235-p5ut64-large.jpg",
  "id" : 56633283,
  "kind" : "user",
  "permalink_url" : "http://soundcloud.com/toofutureshop",
  "uri" : "https://api.soundcloud.com/users/56633283",
  "username" : "TooFuture.",
  "permalink" : "toofutureshop",
  "last_modified" : "2015/05/1716:12:09+0000"
}

 */

public class User {

  
  private String avatar_url;

  
  private Integer id;

  
  private String kind;

  
  private String last_modified;

  
  private String permalink;

  
  private String permalink_url;

  
  private String uri;

  
  private String username;

  public String getAvatar_url() {
    return avatar_url;
  }
  public Integer getId() {
    return id;
  }
  public String getKind() {
    return kind;
  }
  public String getLast_modified() {
    return last_modified;
  }
  public String getPermalink() {
    return permalink;
  }
  public String getPermalink_url() {
    return permalink_url;
  }
  public String getUri() {
    return uri;
  }
  public String getUsername() {
    return username;
  }

  /**
  * Builder for User
  **/
  public static class UserBuilder {
    private User toBuild = new User();

    public UserBuilder() {
    }

    public User build() {
      return toBuild;
    }

    public UserBuilder avatar_url(String value) {
      toBuild.avatar_url = value;
      return this;
    }
    public UserBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public UserBuilder kind(String value) {
      toBuild.kind = value;
      return this;
    }
    public UserBuilder last_modified(String value) {
      toBuild.last_modified = value;
      return this;
    }
    public UserBuilder permalink(String value) {
      toBuild.permalink = value;
      return this;
    }
    public UserBuilder permalink_url(String value) {
      toBuild.permalink_url = value;
      return this;
    }
    public UserBuilder uri(String value) {
      toBuild.uri = value;
      return this;
    }
    public UserBuilder username(String value) {
      toBuild.username = value;
      return this;
    }
  }
}
