/**
 * File generated by Magnet rest2mobile 1.1 - May 20, 2015 11:24:35 AM
 * @see {@link http://developer.magnet.com}
 */

package com.franmondey.soundphone.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "future_href" : "https://api.soundcloud.com/e1/me/stream?uuid%5Bto%5D=41d55725-f380-0000-61c3-cf801b95ffb3&limit=50",
  "collection" : [ {
    "uuid" : "41d55725-f380-0000-61c3-cf801b95ffb3",
    "track" : {
      "artwork_url" : "https://i1.sndcdn.com/artworks-000117434109-3qbumy-large.jpg",
      "comment_count" : 0,
      "commentable" : true,
      "description" : "Info+Tracklist:http://runthetrap.com/2015/05/20/too-future-guest-mix-032-ekali/\n\nEkali\nhttps://soundcloud.com/ekalimusic\nhttps://twitter.com/EkaliMusic\nhttps://www.facebook.com/ekalibeats\n\nTooFuture.\n@toofutureshop\nwww.facebook.com/toofuturexx\nwww.youtube.com/user/toofutureshop\ntwitter.com/toofuture\nwww.instagram.com/toofutureshop\nwww.toofuture.com(beta)",
      "download_count" : 0,
      "downloadable" : false,
      "embeddable_by" : "all",
      "favoritings_count" : 1,
      "genre" : "Ekali",
      "license" : "all-rights-reserved",
      "original_content_size" : 65785179,
      "original_format" : "mp3",
      "playback_count" : 8,
      "reposts_count" : 0,
      "state" : "finished",
        ...

 */

public class FetchSetsResult {

  
  private List<Collection> collection;

  
  private String future_href;

  
  private String next_href;

  public List<Collection> getCollection() {
    return collection;
  }
  public String getFuture_href() {
    return future_href;
  }
  public String getNext_href() {
    return next_href;
  }

  /**
  * Builder for FetchSetsResult
  **/
  public static class FetchSetsResultBuilder {
    private FetchSetsResult toBuild = new FetchSetsResult();

    public FetchSetsResultBuilder() {
    }

    public FetchSetsResult build() {
      return toBuild;
    }

    public FetchSetsResultBuilder collection(List<Collection> value) {
      toBuild.collection = value;
      return this;
    }
    public FetchSetsResultBuilder future_href(String value) {
      toBuild.future_href = value;
      return this;
    }
    public FetchSetsResultBuilder next_href(String value) {
      toBuild.next_href = value;
      return this;
    }
  }
}
