/**
 * File generated by Magnet rest2mobile 1.1 - May 20, 2015 11:24:35 AM
 * @see {@link http://developer.magnet.com}
 */

package com.franmondey.soundphone.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.franmondey.soundphone.controller.api.SoundApi;
import com.franmondey.soundphone.controller.api.SoundApiFactory;
import com.franmondey.soundphone.model.beans.*;

/**
* This is generated stub to test {@link SoundApi}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class SoundApiTest extends InstrumentationTestCase {
  private SoundApi soundApi;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    SoundApiFactory controllerFactory = new SoundApiFactory(magnetClient);
    soundApi = controllerFactory.obtainInstance();

    assertNotNull(soundApi);
  }

  /**
    * Generated unit test for {@link SoundApi#fetchSets}
    */
  @SmallTest
  public void testFetchSets() throws SchemaException, ExecutionException, InterruptedException {
    // FIXME : set proper value for the parameters
    String limit = "50";
    String oauth_token = "1-37435-3000117-83200182126f26e7";
    String format = "json";
    String _statusCodeMap5B3025D = "200";

    Call<FetchSetsResult> callObject = soundApi.fetchSets(
      limit, 
      oauth_token, 
      format, 
      _statusCodeMap5B3025D, null);
    assertNotNull(callObject);

    FetchSetsResult result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
