/**
 * File generated by Magnet rest2mobile 1.1 - May 20, 2015 11:24:35 AM
 * @see {@link http://developer.magnet.com}
 */

package com.franmondey.soundphone.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.franmondey.soundphone.model.beans.*;

public class SoundApiFactory extends ControllerFactory<SoundApi> {
  public SoundApiFactory(MagnetMobileClient magnetClient) {
    super(SoundApi.class, SoundApiSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller SoundApi
  public static class SoundApiSchemaFactory extends AbstractControllerSchemaFactory {
    private static SoundApiSchemaFactory __instance;

    public static synchronized SoundApiSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new SoundApiSchemaFactory();
      }

      return __instance;
    }

    private SoundApiSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method fetchSets
      JMethod method1 = addMethod("fetchSets",
        "e1/me/stream",
        "GET",
        FetchSetsResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("https://api.soundcloud.com");
      method1.addParam("limit",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("oauth_token",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("format",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("_status_code_map%5B302%5D",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
